hebronministries/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('ministries/', views.ministries_index, name='index'),
    path('ministries/<int:ministry_id>/', views.ministries_detail, name='detail'),
    path('ministries/create/', views.MinistryCreate.as_view(), name='ministries_create'),
    path('ministries/<int:pk>/update/', views.MinistryUpdate.as_view(), name='ministries_update'),
    path('ministries/<int:pk>/delete/', views.MinistryDelete.as_view(), name='ministries_delete'),
    path('ministries/<int:ministry_id>/add_event/', views.add_event, name='add_event'),
    path('ministries/<int:ministry_id>/assoc_member/<int:member_id>/', views.assoc_member, name='assoc_member'),
    path('events/', views.events_index, name='events_index'),
    path('events/create/', views.EventCreate.as_view(), name='events_create'),
    path('events/<int:event_id>/', views.events_detail, name='events_detail'),
    path('events/<int:pk>/update/', views.EventUpdate.as_view(), name='events_update'),
    path('events/<int:pk>/delete/', views.EventDelete.as_view(), name='events_delete'),
    path('members/', views.members_index, name='members_index'),
    path('members/create/', views.MemberCreate.as_view(), name='members_create'),
    path('members/<int:member_id>/', views.members_detail, name='members_detail'),
    path('members/<int:pk>/update/', views.MemberUpdate.as_view(), name='members_update'),
    path('members/<int:pk>/delete/', views.MemberDelete.as_view(), name='members_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Member(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('members_detail', kwargs={'member_id': self.id})



class Ministry(models.Model):
    name = models.CharField(max_length=100)
    lead = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    number_of_members = models.IntegerField()

    members = models.ManyToManyField(Member)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'ministry_id': self.id})



class Event(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateField()
    description = models.TextField(max_length=250)
    contact = models.CharField(max_length=100)

    ministry = models.ForeignKey(Ministry, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} on {self.date}"

    class Meta:
        ordering = ['date']





    
    

main_app/forms.py
from django.forms import ModelForm
from .models import Event

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'date', 'description', 'contact']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Ministry, Member, Event
from .forms import EventForm


# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def ministries_index(request):
    ministries = Ministry.objects.all()
    return render(request, 'ministries/index.html', { 'ministries': ministries })

def ministries_detail(request, ministry_id):
    ministry = Ministry.objects.get(id=ministry_id)
    members_not_in_ministry = Member.objects.exclude(id__in = ministry.members.all().values_list('id'))
    # instantiate EventForm to be rendered in the template
    event_form = EventForm()
    return render(request, 'ministries/detail.html', { 
        'ministry': ministry,
        'event_form': event_form,
        'members': members_not_in_ministry
    })

def add_event(request, ministry_id):
    # create a ModelForm instance using the data in request.Post
    form = EventForm(request.POST)
    # validate the form
    if form.is_valid():
        # don't save the form to the db until it has the ministry_id assigned to it. 
        new_event = form.save(commit=False)
        new_event.ministry_id = ministry_id
        new_event.save()
    return redirect('detail', ministry_id=ministry_id)


def events_index(request):
    events = Event.objects.all()
    return render(request, 'events/index.html', { 'events': events })



def events_detail(request, event_id):
    event = Event.objects.get(id=event_id)
    return render(request, 'events/detail.html', {
        'event': event 
    })


class EventCreate(CreateView):
    model = Event
    fields = '__all__'
    success_url = '/events/'

class EventUpdate(UpdateView):
    model = Event
    fields = '__all__'

class EventDelete(DeleteView):
    model = Event
    success_url = '/events/'



class MinistryCreate(CreateView):
    model = Ministry
    fields = '__all__'

class MinistryUpdate(UpdateView):
    model = Ministry
    fields = ['name', 'lead', 'description', 'number_of_members']

class MinistryDelete(DeleteView):
    model = Ministry
    success_url = '/ministries/'


def members_index(request):
    members = Member.objects.all()
    return render(request, 'members/index.html', { 'members': members })

def members_detail(request, member_id):
    member = Member.objects.get(id=member_id)
    return render(request, 'members/detail.html', { 'member': member })


class MemberCreate(CreateView):
    model = Member
    fields = '__all__'

class MemberUpdate(UpdateView):
    model = Member
    fields = '__all__'

class MemberDelete(DeleteView):
    model = Member
    success_url = '/members/'

def assoc_member(request, ministry_id, member_id):
    Ministry.objects.get(id=ministry_id).members.add(member_id)
    return redirect('detail', ministry_id=ministry_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>Hebron EM Ministries</h1>
<hr />
<p>Explore what we have to offer!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Hebron EM</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Hebron EM</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'events_index' %}">Events</a></li>
          <li><a href="{% url 'events_create' %}">Add an Event</a></li>
          
          <li><a href="{% url 'index' %}">Ministries</a></li>
          <li><a href="{% url 'ministries_create' %}">Add a Ministry</a></li>
          <li><a href="{% url 'members_index' %}">Members</a></li>
          <li><a href="{% url 'members_create' %}">Add a Member</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Hebron EM &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/events/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Event Details</h1>
<div class="card">
    <div class="card-content">
        <span class="card-title">{{event.name}}</span>
        <p>Date: {{ event.date}}</p>
        <p>Description: {{ event.description }}</p>
        <p>Contact: {{ event.contact }}</p>
        <p>Ministry: {{ event.ministry }}</p>

    </div>
    <div class="card-action">
        <a href="{% url 'events_update' event.id %}">Edit</a>
        <a href="{% url 'events_delete' event.id %}">Delete</a>
    </div>
</div>
    
{% endblock content %}

main_app/templates/events/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Events List</h1>

{% for event in events  %}
<div class="card">
    <a href="{% url 'events_detail' event.id %}">
        <div class="card-content">
            <span class="card-title">{{ event.name }}</span>
            <p>Date: {{ event.date }}</p>
        </div>        
    </a>
</div>    
{% endfor %}
{% endblock content %}
    

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Home</h1>
    
{% endblock %}
    

main_app/templates/main_app/event_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Event</h1>
<h4>Are you sure you want to delete <span class="teal-text">{{ event.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'events_detail' event.id %}">Cancel</a>
</form>
    
{% endblock content %}
    

main_app/templates/main_app/event_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{ event.name }}</span></h1>
{% else %}
    <h1>Add Event</h1>
{% endif %}
    


<form action="{% url 'events_create' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" class="btn">
</form>

<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        form: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    const ministryEl = document.getElementById('id_ministry');
    M.FormSelect.init(ministryEl);
</script>
    
{% endblock content %}
    

main_app/templates/main_app/member_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Member</h1>
<h4>Are you sure you want to delete <span class="teal-text">{{ member.name }}</span>?</h4>
    
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'members_detail' member.id %}">Cancel</a>

</form>
{% endblock content %}

    

main_app/templates/main_app/member_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
    <h1>Add Member</h1>
{% endif %}
    
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}        
    </table>

    <input type="submit" value="Submit" class="btn">
</form>
    
{% endblock content %}

    

main_app/templates/main_app/ministry_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <h1>Delete Ministry</h1>

    <h4>Are you sure you want to delete <span class="teal-text">{{object.name}}</span>?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="btn">
        <a href="{% url 'detail' ministry.id %}">Cancel</a>
    </form>
    
{% endblock %}
    

main_app/templates/main_app/ministry_form.html
{% extends 'base.html' %}


{% block content %}
    
    <!-- Displays which minitsry is being updated, depending on updating or creating new ministry -->
    {% if object %}
        <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
        <h1>Add Ministry</h1>
    {% endif %}
        
<!-- action left empty to make form post to same url used to display it -->
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>

    <script>
        const membersEl = document.getElementById('id_members');
        M.FormSelect.init(membersEl);
    </script>
    
{% endblock %}
    

main_app/templates/members/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="card">
    <div class="card-content">
        <span class="card-title">{{ member.name }}</span>
        <p>Email: {{ member.email }}</p>
    </div>

    <div class="card-action">
        <a href="{% url 'members_update' member.id %}">Edit</a>
        <a href="{% url 'members_delete' member.id %}">Delete</a>
    </div>

</div>
    
{% endblock content %}


<div class="card">
    <div class="card-content">
        <span class="card-title">{{ ministry.name }}</span>
        <p>Team Lead: {{ ministry.lead }}</p>
        <p>Description: {{ ministry.description }}</p>
        <p>Members: {{ ministry.number_of_members }}</p>
    </div>

    <div class="card-action">
        <a href="{% url 'ministries_update' ministry.id %}">Edit</a>
        <a href="{% url 'ministries_delete' ministry.id %}">Delete</a>
    </div>
</div>

main_app/templates/members/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Member List</h1>

{% for member in members %}
<div class="card">
    <a href="{% url 'members_detail' member.id %}">
        <div class="card-content">
            <span class="card-title">{{ member.name }}</span>
            <p>Email: {{ member.email }}</p>

        </div>        
    </a>


</div>
{% endfor %}
    
    
{% endblock content %}

main_app/templates/ministries/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Ministry Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ ministry.name }}</span>
                <p>Team Lead: {{ ministry.lead }}</p>
                <p>Description: {{ ministry.description }}</p>
                <p>Members: {{ ministry.number_of_members }}</p>
            </div>

            <div class="card-action">
                <a href="{% url 'ministries_update' ministry.id %}">Edit</a>
                <a href="{% url 'ministries_delete' ministry.id %}">Delete</a>
            </div>
        </div>
    </div>

    <div class="col s6">
        <form action="{% url 'add_event' ministry.id %}" method="post">
            {% csrf_token %}
            {{ event_form.as_p }}
            <input type="submit" class="btn" value="Add Event">
        </form>

        <table class="striped">
            <thead>
                <tr><th>Name</th><th>Date</th></tr>
            </thead>
            <tbody>
                {% for event in ministry.event_set.all %}
                    
                        <tr>
                            
                                <td><a href="{% url 'events_detail' event.id%}">{{event.name}}</a></td>
                                <td><a href="{% url 'events_detail' event.id%}">{{event.date}}</a></td>
                            
                        </tr>                        
                    

                {% endfor %}   
            </tbody>
        </table>
    </div>
</div>

<hr>
<div class="row">
    <div class="col s6">
        <h3>Meet the Members of {{ ministry.name }}</h3>
        {% if ministry.members.count %}
            {% for member in ministry.members.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ member.name }}</span>
                        <p>{{ member.email }}</p>
                    </div>
                </div>    
            {% endfor %}
        {% else %}
            <h5>No Members Yet!</h5>
        {% endif %}
    </div>

    <div class="col s6">
        <h3>Available Members</h3>
        
        {% if members.count %}
            
            {% for member in members.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ member.name }}</span>
                    </div>
                
                    <div class="card-action">
                        <form action="{% url 'assoc_member' ministry.id member.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn">Add</button>
                        </form>

                    </div>

                </div>
            {% endfor %}
                
        {% else %}
            <h5>No Members Available to Add</h5>
        {% endif %}
            

    </div>

</div>


<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        form: 'yyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
</script>

{% endblock %}
    

main_app/templates/ministries/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Ministry List</h1>


{% for ministry in ministries  %}
    <div class="card">
        <a href="{% url 'detail' ministry.id %}">
        <div class="card-content">
            <span class="card-title">{{ ministry.name }}</span>
            <p>Team Lead: {{ ministry.lead }}</p>
            <p>Description: {{ ministry.description }}</p>
            <p>Members: {{ ministry.number_of_members }}</p>
        </div>
        </a>
    </div>
{% endfor %}
    
{% endblock %}
    